name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/**.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1